version: "3.4"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
#      KAFKA_BROKERCONNECT: "10.1.1.51:9092"
      KAFKA_BROKERCONNECT: "localhost:9092"
      JVM_OPTS: "-Xms32M -Xmx96M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
